### ISSUE TITLE
I find a issue in CmakeLists.txt

### ISSUE THREAD

**Issue by dttlgotv** [xs-embedded-llc/cdbus#1]
Hi,

When I make cdbus, a error is fould like below :
      CMake Error at CMakeLists.txt:241 (add_dependencies):
     add_dependencies Adding dependency to non-existent target:
     CDBUS_MAIN_LOOP_EV_SHARED

Line 241 in file CMakeLists.txt is   "add_dependencies(CDBUS_MAIN_LOOP_EV_SHARED CDBUS_SHARED)", it looks conflict with line 240 " add_dependencies(CDBUS_MAIN_LOOP_GLIB_SHARED CDBUS_MAIN_LOOP_GLIB_STATIC)".

Even NOT CDBUS_NO_GLIB_LOOP is used in line 221, why "add_dependencies(CDBUS_MAIN_LOOP_GLIB_SHARED CDBUS_MAIN_LOOP_GLIB_STATIC)" is used?

So I just delete the line 240 in CMakeLists.txt, then cdbus can be compiled successfully.

Best,
John

**Comment by gschmottlach-xse** [comment]
Thank you for the bug report. I believe this was a copy-paste error in the CMakeLists.txt file where CDBUS_MAIN_LOOP_GLIB_SHARED should have been used on line 241 rather than CDBUS_MAIN_LOOP_EV_SHARED. This has been corrected (see commit b954363). Please let us know if it fixes your problem.

**Comment by dttlgotv** [comment]
work well using b954363.
Thanks a lot.
